package:
  name: prefect-test-skip-dependency
  version: 1.0
source:
  path: ../src
build:
  number: 2
  skip: True # [win]
about:
  home: https://github.com/AnacondaRecipes/prefect-test-skip-dependency-feedstock
  license_file: LICENSE
  license: BSD-3-Clause
  license_family: BSD
extra:
  recipe-maintainers:
    - dkomisar
